"""Create a Typesense collection from category definitions with vector embeddings."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Iterable, Dict, Any, List

from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
import typesense

from process_categories import load_categories


CollectionDocument = Dict[str, Any]


def read_jsonl(path: Path) -> List[CollectionDocument]:
    documents: List[CollectionDocument] = []
    with path.open("r", encoding="utf-8") as fp:
        for line in fp:
            line = line.strip()
            if not line:
                continue
            documents.append(json.loads(line))
    return documents


def get_documents(args: argparse.Namespace) -> List[CollectionDocument]:
    if args.documents_path:
        return read_jsonl(args.documents_path)
    return load_categories(
        excel_path=args.excel_path,
        sheet_name=args.sheet_name,
        category_column=args.category_column,
        definition_column=args.definition_column,
        metadata_columns=args.metadata_columns,
    )


def ensure_collection(
    client: typesense.Client,
    collection_name: str,
    embedding_dim: int,
    sample_document: CollectionDocument,
    distance: str = "cosine",
) -> None:
    fields = [
        {"name": "id", "type": "string"},
        {"name": "category", "type": "string"},
        {"name": "definition", "type": "string"},
        {
            "name": "embedding",
            "type": "float[]",
            "num_dim": embedding_dim,
        },
    ]

    for key, value in sample_document.items():
        if key in {"id", "category", "definition", "embedding"}:
            continue
        field_type = "float" if isinstance(value, (int, float)) else "string"
        fields.append({"name": key, "type": field_type, "optional": True})

    schema = {
        "name": collection_name,
        "fields": fields,
        "vector": {"size": embedding_dim, "distance": distance},
    }

    try:
        client.collections.create(schema)
        print(f"Created collection '{collection_name}'.")
    except typesense.exceptions.ObjectAlreadyExists:
        print(f"Collection '{collection_name}' already exists. Using existing collection.")


def embed_documents(
    model: SentenceTransformer, documents: Iterable[CollectionDocument]
) -> List[CollectionDocument]:
    documents_with_embeddings: List[CollectionDocument] = []
    sentences = [f"{doc['category']}\n{doc['definition']}" for doc in documents]
    embeddings = model.encode(sentences, convert_to_numpy=True, normalize_embeddings=True)
    for doc, embedding in zip(documents, embeddings):
        enriched = dict(doc)
        enriched["embedding"] = embedding.tolist()
        documents_with_embeddings.append(enriched)
    return documents_with_embeddings


def upsert_documents(
    client: typesense.Client,
    collection_name: str,
    documents: Iterable[CollectionDocument],
) -> None:
    payload = "\n".join(json.dumps(doc, ensure_ascii=False) for doc in documents)
    result = client.collections[collection_name].documents.import_(payload, {
        "action": "upsert"
    })
    print(result)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Index category embeddings into Typesense")

    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument(
        "--documents-path",
        type=Path,
        help="Path to a JSONL file generated by process_categories.py",
    )
    source_group.add_argument(
        "--excel-path",
        type=Path,
        help="Path to the Excel workbook to read directly",
    )

    parser.add_argument("--sheet-name", type=str, default=None)
    parser.add_argument("--category-column", type=str, default="Category")
    parser.add_argument("--definition-column", type=str, default="Definition")
    parser.add_argument("--metadata-columns", nargs="*", default=())
    parser.add_argument("--collection", type=str, default="category_definitions")
    parser.add_argument(
        "--model-name",
        type=str,
        default="sentence-transformers/all-MiniLM-L6-v2",
        help="SentenceTransformer model to use for embeddings",
    )
    parser.add_argument("--host", type=str, default=None)
    parser.add_argument("--port", type=int, default=None)
    parser.add_argument("--protocol", type=str, default=None)
    parser.add_argument("--api-key", type=str, default=None)
    parser.add_argument(
        "--environment",
        action="store_true",
        help="Load Typesense credentials from a .env file if present",
    )
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.environment:
        load_dotenv()

    host = args.host or os.environ.get("TYPESENSE_HOST", "localhost")
    port = args.port or int(os.environ.get("TYPESENSE_PORT", 8108))
    protocol = args.protocol or os.environ.get("TYPESENSE_PROTOCOL", "http")
    api_key = args.api_key or os.environ.get("TYPESENSE_API_KEY")
    if not api_key:
        raise ValueError("Typesense API key must be provided via --api-key or environment")

    documents = get_documents(args)
    if not documents:
        raise ValueError("No documents to index")

    model = SentenceTransformer(args.model_name)
    enriched_documents = embed_documents(model, documents)

    client = typesense.Client(
        {
            "nodes": [{"host": host, "port": port, "protocol": protocol}],
            "api_key": api_key,
            "connection_timeout_seconds": 10,
        }
    )

    ensure_collection(client, args.collection, model.get_sentence_embedding_dimension(), documents[0])
    upsert_documents(client, args.collection, enriched_documents)
    print(f"Indexed {len(enriched_documents)} documents into '{args.collection}'.")


if __name__ == "__main__":
    main()
